// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdwqfzskgtpscyzopvnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkd3FmenNrZ3Rwc2N5em9wdm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzMwMzQsImV4cCI6MjA3NDMwOTAzNH0.fk8OVkIqUHT8sWTAe6wbKvGGtp9KR37gyfTc2ip42y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});